Update buildAndUpdate.yml

diff --git a/.github/workflows/buildAndUpdate.yml b/.github/workflows/buildAndUpdate.yml
--- a/.github/workflows/buildAndUpdate.yml
+++ b/.github/workflows/buildAndUpdate.yml
@@ -6,6 +6,13 @@ jobs:
     name: EAS build and update android
     runs-on: ubuntu-latest
     steps:
+      - name: Check for ENV_FILE
+        run: |
+          if [ -z "${{ secrets.ENV_FILE }}" ]; then
+            echo "ENV_FILE is missing"
+            exit 1
+          fi
+    
       - name: Check for EXPO_TOKEN
         run: |
           if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
@@ -42,6 +49,11 @@ jobs:
       
       - name: Install dependencies
         run: yarn install --immutable
+
+      - name: Create .env File
+        run: |
+          touch .env
+          echo "${{ secrets.ENV_FILE}}" >> .env
 
       - name: Create build android
         run: eas build --profile main --platform android --no-wait --non-interactive
