Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -6,13 +6,15 @@ jobs:
     name: Expo build android
     runs-on: ubuntu-latest
     steps:
-      - name: Make envfile
-        uses: SpicyPizza/create-envfile@v1.3
-        with:
-          envkey_DEBUG: false
-          envkey_SOME_API_KEY: "45as4dass98d"
-          envkey_SECRET_KEY: "as4d847as8da"
-          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
+      - name: Check for ENV_FILE
+        run: |
+          if [ -z "${{ secrets.ENV_FILE }}" ]; then
+            echo "ENV_FILE is missing"
+            exit 1
+          fi
+
+      - name: Create .env File
+        run: echo "${{ secrets.ENV_FILE}}" > ../../.env
 
       - name: Check for EXPO_TOKEN
         run: |
